name: "Policy Logout"
description: "Logout from Open Policy Registry (opcr.io)"
author: "Aserto Inc."
branding:
  icon: log-out
  color: blue
inputs:
  server:
    description: "registry service hostname"
    required: true
    default: "opcr.io"
  verbosity:
    description: "verbosity level [info|error|debug|trace]"
    required: true
    default: error
runs:
  using: docker
  image: 'docker://ghcr.io/opcr-io/policy:0.2'
  entrypoint: /app/logout.sh
